/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat (TomEE)/7.0.55 (1.7.1)
 * Generated at: 2016-04-22 13:59:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import java.util.Map;
import car.tp4.*;

public final class panier_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<style type=\"text/css\">\n");
      out.write("td {\n");
      out.write("\tborder: 1px solid black;\n");
      out.write("\tpadding: 5px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("input[type=\"text\"][readonly] {\n");
      out.write("\tcolor: black;\n");
      out.write("\tborder: none;\n");
      out.write("\tbackground: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("table {\n");
      out.write("\tmargin-bottom: 10px;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t");

		Panier panier = (Panier) application.getAttribute("PANIER");
		String commande_state = request.getParameter("commande");
		if (commande_state != null && commande_state.equals("valide")) {
			out.print("<p><b>Commande : </b></p>");

			ListeCommandes commandes = (ListeCommandes) application.getAttribute("COMMANDES");

			if (commandes != null && panier != null) {
				commandes.add(new Commande(panier));
			}
		} else {
			out.print("<p><b>Panier : </b></p>");
		}
	
      out.write("\n");
      out.write("\n");
      out.write("\t<table>\n");
      out.write("\n");
      out.write("\t\t");

			if (panier != null) {
				Map<Livre, Integer> livres = panier.getListeLivre();

				out.print("<tr><td>Titre<td>Auteur</td><td>Année</td><td>Quantité</td></tr>");

				for (Map.Entry<Livre, Integer> entry : livres.entrySet()) {
					Livre livre = entry.getKey();

					out.print("<tr>");
					out.print("<td>" + livre.getTitre() + "</td>");
					out.print("<td>" + livre.getAuteur() + "</td>");
					out.print("<td>" + livre.getAnnee() + "</td>");
					out.print("<td>" + entry.getValue() + "</td>");

					out.print("</tr>");
					out.print("</form>");
				}
			}
		
      out.write("\n");
      out.write("\t</table>\n");
      out.write("\t");

		if (commande_state == null) {
	
      out.write("\n");
      out.write("\t<form action=\"panier.jsp\" method=\"get\">\n");
      out.write("\t\t<input type=\"hidden\" value=\"valide\" name=\"commande\"> <input\n");
      out.write("\t\t\ttype=\"submit\" value=\"Passer commande\">\n");
      out.write("\t</form>\n");
      out.write("\t");

		} else {
			panier.clear();
		}
	
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
