/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat (TomEE)/7.0.55 (1.7.1)
 * Generated at: 2016-04-25 21:45:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import java.util.Map;
import car.tp4.*;

public final class basket_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\"/>\r\n");
      out.write("\t<title>BibliothÃ¨que | Panier</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/css/materialize.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"navbar-fixed\">\r\n");
      out.write("\t  <nav>\r\n");
      out.write("      <div class=\"nav-wrapper teal lighten-1\">\r\n");
      out.write("        <a href=\"#\" class=\"brand-logo right\">CAR-TP4</a>\r\n");
      out.write("        <ul id=\"nav-mobile\" class=\"left hide-on-med-and-down\">\r\n");
      out.write("          <li><a href=\"books.jsp\">Library</a></li>\r\n");
      out.write("          <li><a href=\"authors.jsp\">Authors</a></li>\r\n");
      out.write("          <li><a href=\"basket.jsp\">My Basket</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("  \t  </nav>\r\n");
      out.write("  \t</div>\r\n");
      out.write("\t");

		Basket basket = (Basket) application.getAttribute("BASKET");
		String cmd = request.getParameter("commande");
		if (cmd != null && cmd.equals("valide")) {
			out.print("<p><b>Commande : </b></p>");

			ListeCommandes commandes = (ListeCommandes) application.getAttribute("COMMANDES");

			if (commandes != null && basket != null) {
				commandes.add(new Commande(basket));
			}
		} else {
			out.print("<p><b>Basket : </b></p>");
		}
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<table>\r\n");
      out.write("\r\n");
      out.write("\t\t");

			if (basket != null) {
				Map<Book, Integer> books = basket.getBasket();

				out.print("<tr><td>Title<td>Author</td><td>Year</td><td>Qte</td></tr>");

				for (Map.Entry<Book, Integer> map : books.entrySet()) {
					Book b = map.getKey();

					out.print("<tr>");
					out.print("<td>" + b.getTitle() + "</td>");
					out.print("<td>" + b.getAuthor() + "</td>");
					out.print("<td>" + b.getYear() + "</td>");
					out.print("<td>" + map.getValue() + "</td>");

					out.print("</tr>");
					out.print("</form>");
				}
			}
		
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("\t");

		if (cmd == null) {
	
      out.write("\r\n");
      out.write("\t<form action=\"basket.jsp\" method=\"get\">\r\n");
      out.write("\t\t<input type=\"hidden\" value=\"valide\" name=\"commande\"> <input\r\n");
      out.write("\t\t\ttype=\"submit\" value=\"Passer commande\">\r\n");
      out.write("\t</form>\r\n");
      out.write("\t");

		} else {
			basket.clear();
		}
	
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("td {\r\n");
      out.write("\tborder: 1px solid black;\r\n");
      out.write("\tpadding: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=\"text\"][readonly] {\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tbackground: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table {\r\n");
      out.write("\tmargin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("</style>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
